name: Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    # 00:00 on Saturdays
    - cron: '0 0 * * SAT'
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '2'

      - name: Test on Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.0
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
      - run: npx prettier --check .
      - run: npm run lint
      - run: npm run build
      - run: npm run test
      - run: npx testpack-cli --keep=@types/jest,ts-jest,typescript src/e2e.spec.ts

      - name: Upload test coverage report to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          fail_ci_if_error: true

      - name: Run Snyk to check for vulnerabilities
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
